notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d3ccde49414baafc4060
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
node_js:
- "0.10"
- "0.12"
- "iojs"
language: node_js
before_install: npm install -g grunt-cli
install: npm install
